name: kyron
description: A Mediator pattern implementation for Dart.
version: 0.5.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  meta: ^1.16.0
  logging: ^1.3.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  mocktail: ^1.0.4
  test: ^1.24.0
