name: request_handler_communication_example
description: Demonstrates basic request/handler communication using the Kyron mediator.
publish_to: 'none' # Prevent accidental publishing

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # When running this example from within the kyron package structure:
  kyron:
    path: ../../
  logging: ^1.3.0 # Kyron uses logging, useful to see output

dev_dependencies:
  lints: ^4.0.0